# Commands
PYTHON ?= python3
CARGO  ?= cargo
SYMBOL ?= 

.PHONY: help fmt check test test-py verify run backtest export collect consolidate setup clean

# Default target
help:
	@echo "Hope Trading Engine - Development Commands"
	@echo "=========================================="
	@echo "fmt         : Format source code"
	@echo "check       : Run cargo check (offline)"
	@echo "test        : Run Rust unit tests (offline)"
	@echo "test-py     : Run Python unit tests"
	@echo "verify      : Format, check, and test everything"
	@echo "verify-stats : Run statistical integrity verification"
	@echo "run         : Start the trading engine"
	@echo "backtest    : Run strategy backtesting on data/ticks.csv"
	@echo "export      : Export ticks from SQLite to data/ticks.csv (use SYMBOL=R_100)"
	@echo "collect     : Collect historical ticks from Deriv API"
	@echo "consolidate : Generate an audit snapshot of the project"
	@echo "setup       : Install Python dependencies from requirements.txt"
	@echo "clean       : Remove audit logs and temporary artifacts"

fmt:
	$(CARGO) fmt

check:
	$(CARGO) check --locked --offline

test:
	$(CARGO) test --locked --offline

test-py:
	$(PYTHON) -m pytest tests/

verify: fmt check test test-py verify-stats

verify-stats:
	$(CARGO) test --test verification --locked --offline -- --nocapture

run:
	$(CARGO) run --locked --offline

backtest:
	$(CARGO) run --bin backtest --locked --offline

train:
	@echo "NOTICE: Invoking training directly on local machine is prohibited. Upload data/ticks.csv to Kaggle/Colab and execute the notebooks generated by restore_nb.py."

restore-nb:
	$(PYTHON) restore_nb.py
	@echo "Notebooks restored. Run 'git add notebooks/' to commit."

export:
	@_SYMBOL=$$(sed -n 's/^DERIV_SYMBOL=\([^#[:space:]]*\).*/\1/p' .env 2>/dev/null); \
	TARGET_SYMBOL=$${SYMBOL:-$${_SYMBOL:-R_100}}; \
	echo "Exporting ticks for symbol: $$TARGET_SYMBOL"; \
	$(PYTHON) scripts/export_db.py --symbol $$TARGET_SYMBOL --incremental --validate

collect:
	@_SYMBOL=$$(sed -n 's/^DERIV_SYMBOL=\([^#[:space:]]*\).*/\1/p' .env 2>/dev/null); \
	TARGET_SYMBOL=$${SYMBOL:-$${_SYMBOL:-R_100}}; \
	TARGET_MODE=$${MODE:-backfill}; \
	echo "Collecting ticks for symbol: $$TARGET_SYMBOL (Mode: $$TARGET_MODE)"; \
	$(PYTHON) scripts/tick_collector.py --symbol $$TARGET_SYMBOL --mode $$TARGET_MODE

consolidate:
	$(PYTHON) consolidate_project_sources.py

setup:
	$(PYTHON) -m pip install -r requirements.txt

clean:
	@echo "Removing logs and snapshots only."
	rm -f tick_audit.log *_merged_sources.txt project_snapshot.txt
	$(CARGO) clean

clean-all:
	@echo "WARNING: permanently deleting locally collected data/ticks.csv"
	@echo "You will need to re-run make collect and make export to restore the dataset."
	rm -f tick_audit.log *_merged_sources.txt data/ticks.csv project_snapshot.txt
	$(CARGO) clean
